name:                   example-processor
version:                0.1.0.0
synopsis:               A simple processor example using Haskell and NATS.
#description:
github:                 dogonthehorizon/git-config
license:                BSD3
author:                 Fernando Freire
copyright:              2018 Fernando Freire
category:               Web,Kubernetes,NATS
extra-source-files:
  - README.md

dependencies:
  - base >= 4.7 && < 5
default-extensions:
  - OverloadedStrings
ghc-options:
  - -Wall
  - -fno-warn-partial-type-signatures
  - -fno-warn-name-shadowing
  - -fwarn-tabs
  - -fwarn-unused-imports
  - -fwarn-missing-signatures
  - -fwarn-incomplete-patterns

executables:
  example-processor:
    source-dirs:        src
    main:               Main.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - nats-queue

tests:
  git-config-test:
    main: Tasty.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - example-processor
      - smallcheck
      - tasty
      - tasty-discover
      - tasty-hunit
      - tasty-smallcheck
